# docker-compose --log-level INFO up --build  
# docker-compose --log-level INFO up -d --build

version: '3'
services:
  public-note:
    stdin_open: true
    tty: true
    image: b3log/siyuan:v3.0.3
    ports:
      - "6808:6806"
    environment:
      - "TZ=CST-8"
    volumes:
      - ./workspace:/home/siyuan
    restart: "no"
#    networks:
#      - public_note_blog_network
#
#  public-blog:
#    image: terwer/nuxt3-blog:latest
#    ports:
#      - "3333:3000"
#    env_file:
#      - ./.env.docker
#    networks:
#      - public_note_blog_network
#
#networks:
#  public_note_blog_network:
