# docker-compose --log-level INFO up --build  
# docker-compose --log-level INFO up -d --build

version: '3'
services:
  note:
    stdin_open: true
    tty: true
    image: b3log/siyuan:v2.9.2
    ports:
      - "6808:6806"
    environment:
      - "TZ=CST-8"
    volumes:
      - ./workspace:/home/siyuan/Documents
    restart: "no"
    networks:
      - note_blog_network

  blog:
    image: terwer/nuxt3-blog:1.2.0
    ports:
      - "3333:3000"
    env_file:
      - ./.env.docker
    networks:
      - note_blog_network

networks:
  note_blog_network: