# docker-compose --log-level INFO up --build  
# docker-compose --log-level INFO up -d --build

version: '3'
services:
  prd-note:
    stdin_open: true
    tty: true
    image: terwer/my-note-docker-private:latest
    container_name: my-note-docker-private
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6807:6806"
    environment:
      # 最好使用此设定时区，其它镜像也可以使用，也可以用"TZ=Asia/Shanghai"
      - "TZ=CST-8"
    volumes:
      - ./workspace:/home/siyuan/Documents
    restart: "no"