# docker-compose --log-level INFO up --build  
# docker-compose --log-level INFO up -d --build

version: '3'
services:
  note:
    stdin_open: true
    tty: true
    image: b3log/siyuan:v2.9.1
    ports:
      - "6808:6806"
    environment:
      - "TZ=CST-8"
    volumes:
      - ./workspace:/home/siyuan/Documents
    restart: "no"
    networks:
      - note_blog_network

#  blog:
#    image: terwer/vue3-ssr:latest
#    ports:
#      - "3333:3333"
#    env_file:
#      - ./.env.docker
#    environment:
#      VITE_SIYUAN_API_URL: http://note:6806
#    networks:
#      - note_blog_network

networks:
  note_blog_network: