# docker-compose --log-level INFO up --build  
# docker-compose --log-level INFO up -d --build

version: '3'
services:
  private:
    build: .
    container_name: my-note
    ports:
      - "6807:6806"
    environment:
      - "TZ=CST-8"
    command: --accessAuthCode=123456
    volumes:
      - ./workspace:/home/siyuan/Documents
    restart: "no"
#    networks:
#      - private_note_blog_network
#
#  private-blog:
#    image: terwer/nuxt3-blog:latest
#    ports:
#      - "3333:3000"
#    env_file:
#      - ./.env.docker
#    networks:
#      - private_note_blog_network
#
#networks:
#  private_note_blog_network: