# docker-compose --log-level INFO up --build
# docker-compose --log-level INFO up -d --build

version: '3'
services:
  my-note-docker:
    stdin_open: true
    tty: true
    container_name: my-note-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6806:6806"
    environment:
      # 最好使用此设定时区，其它镜像也可以使用，也可以用"TZ=Asia/Shanghai"
      - "TZ=CST-8"
    volumes:
      - ./workspace:/home/siyuan/Documents
    restart: "no"